logging:
  level:
    ROOT: DEBUG
    com.vishal.transactions: DEBUG
    
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transactions
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    