logging:
  level:
    ROOT: DEBUG
    com.vishal.transactions: DEBUG

server:
  port: 8080
    
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    